version: "3.7"
services:
  infra:
    build:
      dockerfile: docker/Dockerfile
      context: .
    working_dir: /infra/env/${ENVIRONMENT}
    volumes:
      - ./:/infra
      - ~/.kube/config:/root/.kube/config
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_VAULT=${AWS_VAULT}
      - AWS_USER=${AWS_USER}
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - ENVIRONMENT=${ENVIRONMENT}
